site_name: "Programação Web 1"
site_description: "Material do Curso de Programação Web 1 do curso de Técnico em Desenvolvimento de Sistemas do IFAL"
site_url: "https://<github-username>.github.io/<book-repo-name>/"
repo_url: "https://github.com/leofernandesmo/pweb1-book/"
repo_name: "GitHub"

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - content.action.view
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/<your-github-username>"

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - print-site:
      add_to_navigation: true
      print_page_title: "Print / Save PDF"  


extra_javascript:
  - assets/js/quiz.js
  - assets/js/code-runner.js

extra_css:
  - assets/extra.css
  - assets/css/custom.css

nav:
  - Home: index.md
  - Cover: cover.md
  - Title Page: title-page.md
  - Preface: preface.md
  - Chapters:
      - "0. Como User Este Material": chapters/00-how-to-use.md
      - "1. Introdução a Web e Navegadores": chapters/01-introducao.md
      - "2. Fundamentos do HTML": chapters/02-html-fundamentos.md
      - "3. HTML Semântico": chapters/03-html-semantico.md
      - "4. Tabelas, Listas e Mídia": chapters/04-tabelas-listas-midia.md      
      - "5. Formulários HTML": chapters/05-formularios.md      
      - "6. Acessibilidade": chapters/06-acessibilidade.md 
      - "7. Em Construção": chapters/07-css-fundamentos.md 
      - "8. Em Construção": chapters/08-flexbox.md 
      - "9. Em Construção": chapters/09-grid.md 
      - "10. Em Construção": chapters/10-responsivo.md 
      - "11. Em Construção": chapters/11-design-system.md 
      - "12. Em Construção": chapters/12-tailwind.md 
      - "13. Em Construção": chapters/13-javascript-essencial.md 
      - "14. Em Construção": chapters/14-dom.md 
      - "15. Em Construção": chapters/15-validacao-forms.md 
      - "16. Em Construção": chapters/16-apis.md 
      - "17. Em Construção": chapters/17-frontend-api.md 
      - "18. Em Construção": chapters/18-projeto-final.md       
      - "Appendix": chapters/99-appendix.md      
  - Back Cover: back-cover.md
